version: '3.8'

services:
    utility-bot:
        # image: docker_id/docker_hub_repo:tag
        build:
            context: ..
            dockerfile: .dockerenv/Dockerfile
        container_name: utility-bot
        restart: unless-stopped
        environment:
            # NOTE: up to 4 bot tokens

            UTILITY_BOT_TOKEN: your-utility-token
            #UTILITY_BOT1_TOKEN: your-utility-token1
            #UTILITY_BOT2_TOKEN: your-utility-token2
            #UTILITY_BOT3_TOKEN: your-utility-token3

            LOG_LEVEL: DEBUG # INFO, ERROR, WARN

            UTILITY_BOT_LOG_LEVEL: INFO # DEBUG, ERROR, WARN
            #UTILITY_BOT1_LOG_LEVEL: WARN
            #UTILITY_BOT2_LOG_LEVEL: WARN
            #UTILITY_BOT3_LOG_LEVEL: WARN

            LOGGER_SHOW_TIMESTAMP: true

            # if true, the bots will register their slash commands
            # on start in all the servers thay are part of
            REGISTER_SLASH_COMMANDS: true

            # The Following options match the postgres service
            POSTGRES_DB: discord_bot
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432

        depends_on:
            postgres:
                condition: service_started


    postgres:
        image: postgres:14.1-alpine
        container_name: postgres
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: discord_bot
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres-data:/var/lib/postgresql/data


volumes:
    postgres-data:
        driver: local
